# Telegram Bot Token Generator for Railway Monitoring
# This script helps create a Telegram bot for monitoring

# Bot Father Commands Reference
echo "🤖 Telegram Bot Setup Instructions"
echo "================================="
echo ""
echo "1. Open Telegram and go to @BotFather"
echo "2. Send the following commands:"
echo ""
echo "/newbot"
echo "Enter bot name: PromptMasterPro Monitor"
echo "Enter username: @pmp_monitor_bot (must be unique)"
echo ""
echo "3. Copy the token that BotFather gives you"
echo "4. Use the token in Railway setup"
echo ""
echo "Example token format:"
echo "123456789:ABCdefGHIjklMNOpqrsTUVwxyz"
echo ""
echo "Additional BotFather commands you might want to use:"
echo "/setdescription - Set bot description"
echo "/setabouttext - Set about text"
echo "/setuserpic - Set bot profile picture"
echo "/setcommands - Set bot commands"
echo ""
echo "🎯 For monitoring setup, you'll also need:"
echo "1. Your Telegram Chat ID (message @userinfobot)"
echo "2. Or Group Chat ID (add bot to group and use @userinfobot)"
echo ""
echo "📋 Ready to continue with Railway setup?"
echo "Once you have your bot token, run:"
echo "railway variables --set \"TELEGRAM_BOT_TOKEN=your_token_here\""